language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"
    - "pypy"
install:
    - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then travis_retry pip install -r requirements2.txt; fi
    - travis_retry pip install -r requirements.txt
    - travis_retry python setup.py install
script:
    - python setup.py test
